"""
Django settings for heladeria_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production production!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-tu-clave-secreta-local')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,yoheladeria.onrender.com').split(',')
# ... (otras configuraciones) ...

# --- INICIO: NUEVAS LÍNEAS PARA CSRF_TRUSTED_ORIGINS ---
# Esto es crucial para despliegues donde el dominio no es localhost
CSRF_TRUSTED_ORIGINS = [
    'https://yoheladeria.onrender.com', # <-- Añade la URL completa de tu dominio en Render
    # Si usas algún subdominio personalizado en el futuro, también deberás añadirlo aquí.
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pedidos',   # <-- NUESTRA APP DE PEDIDOS
    'channels',  # <-- ¡NUEVA LÍNEA AQUÍ!
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heladeria_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'pedidos', 'templates'), # Agrega esta línea
        ],
        'APP_DIRS': True, # Mantener en True para buscar en otras apps si hay
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'heladeria_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        conn_max_age=600,
        default='sqlite:///db.sqlite3'
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static', # AHORA APUNTA A LA CARPETA STATIC GLOBAL DEL PROYECTO
]

# Configuración para archivos de Medios (Imágenes de productos, etc.)
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# --- INICIO: REDIRECCIONES DE AUTENTICACIÓN (MOVIDO Y CORREGIDO) ---
LOGIN_REDIRECT_URL = '/'  # URL a la que el usuario será redirigido después de iniciar sesión con éxito.
LOGOUT_REDIRECT_URL = '/' # URL a la que el usuario será redirigido después de cerrar sesión con éxito.
LOGIN_URL = '/accounts/login/' # URL de la página de inicio de sesión si el usuario no está autenticado.
# --- FIN: REDIRECCIONES DE AUTENTICACIÓN ---

# --- INICIO: CONFIGURACIÓN DE DJANGO CHANNELS (PARA DESARROLLO SIN REDIS) ---
ASGI_APPLICATION = 'heladeria_backend.asgi.application' # El punto de entrada para ASGI

# Configuración de los Channel Layers (para comunicación en tiempo real)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer', # <-- ¡CAMBIO CLAVE AQUÍ! Usamos la capa en memoria
    },
}
# --- FIN: CONFIGURACIÓN DE DJANGO CHANNELS ---