# Generated by Django 5.2.4 on 2025-07-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_direccion', models.CharField(max_length=255)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En Preparación'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto.', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio base del producto. Las opciones pueden tener precios adicionales.', max_digits=10)),
                ('sabores_maximos', models.PositiveIntegerField(default=0, help_text='Número máximo de sabores a elegir para este producto. Cero si no permite elección de sabores (ej. tortas, palitos).')),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, help_text="Ruta a la imagen estática del producto base (ej: 'images/pote_1_5kg.png')", max_length=255, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='pedidos.categoria')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OpcionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_opcion', models.CharField(help_text="Nombre específico de la opción (ej. 'Sabor Selva Negra', 'Dulce de Leche y Americana').", max_length=150)),
                ('descripcion_opcion', models.TextField(blank=True, help_text='Descripción detallada de esta opción.', null=True)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio adicional si esta opción es más cara que el producto base.', max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen_opcion', models.CharField(blank=True, help_text="Ruta a la imagen estática de esta opción (ej: 'images/torta_selva_negra.png')", max_length=255, null=True)),
                ('producto_base', models.ForeignKey(help_text="El producto genérico al que pertenece esta opción (ej. 'Torta Helada', 'Palito Bomboneiro').", on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='pedidos.producto')),
            ],
            options={
                'verbose_name': 'Opción de Producto',
                'verbose_name_plural': 'Opciones de Productos',
                'unique_together': {('producto_base', 'nombre_opcion')},
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.opcionproducto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.producto')),
                ('sabores', models.ManyToManyField(to='pedidos.sabor')),
            ],
        ),
    ]
