# Generated by Django 5.2.4 on 2025-07-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
