# Generated by Django 5.2.4 on 2025-07-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_detallepedido_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del producto o descuento a canjear (ej: '1 Kg de Helado GRATIS', '50% Descuento en Tortas').", max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la recompensa.', null=True)),
                ('puntos_requeridos', models.PositiveIntegerField(default=0, help_text='Cantidad de puntos de fidelidad necesarios para canjear este ítem.')),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.CharField(blank=True, help_text="Ruta a la imagen estática del producto canjeable (ej: 'images/canje_kilo.png')", max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Producto de Canje',
                'verbose_name_plural': 'Productos de Canje',
                'ordering': ['puntos_requeridos', 'nombre'],
            },
        ),
    ]
