# Generated by Django 5.2.4 on 2025-07-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_productocanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'Mercado Pago')], default='EFECTIVO', max_length=20),
        ),
    ]
