# Generated by Gemini
from django.db import migrations

def limpiar_base_de_datos(apps, schema_editor):
    # Obtenemos los modelos que queremos limpiar
    DetallePedido = apps.get_model('pedidos', 'DetallePedido')
    Pedido = apps.get_model('pedidos', 'Pedido')
    Producto = apps.get_model('pedidos', 'Producto')
    Sabor = apps.get_model('pedidos', 'Sabor')
    User = apps.get_model('auth', 'User')

    print("\nLimpiando base de datos...")
    # Borramos en orden para evitar errores de protección de datos
    DetallePedido.objects.all().delete()
    Pedido.objects.all().delete()
    Producto.objects.all().delete()
    Sabor.objects.all().delete()
    # Opcional: Borramos todos los usuarios menos el primer superusuario si quisiéramos mantenerlo
    # En este caso, borraremos todos para empezar 100% de cero.
    #User.objects.exclude(is_staff=False).delete() # Borra solo usuarios no-staff, para no borrar el admin
    print("Limpieza completada.")

class Migration(migrations.Migration):

    dependencies = [
        # Reemplaza '0006_cargar_menu_final' con el nombre de tu última migración
        ('pedidos', '0006_cargar_menu_final'),
    ]

    operations = [
        migrations.RunPython(limpiar_base_de_datos),
    ]
