# Generated by Django 5.2.4 on 2025-07-29 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_pedido_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la zona de envío (ej: Centro, Norte, Sur).', max_length=100, unique=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo de envío para esta zona.', max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zona de Envío',
                'verbose_name_plural': 'Zonas de Envío',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='zona_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_en_zona', to='pedidos.zonaenvio'),
        ),
    ]
