# Generated by Django 5.2.4 on 2025-07-31 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_zonaenvio_pedido_zona_envio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadeteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Número de teléfono único del cadete.', max_length=20, unique=True)),
                ('vehiculo', models.CharField(choices=[('MOTO', 'Motocicleta'), ('BICI', 'Bicicleta'), ('AUTO', 'Automóvil')], default='MOTO', max_length=4)),
                ('disponible', models.BooleanField(default=False, help_text='Marcar si el cadete está disponible para recibir pedidos.')),
                ('latitud_actual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_actual', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadeteprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Cadete',
                'verbose_name_plural': 'Perfiles de Cadetes',
            },
        ),
    ]
