# Generated by Django 5.2.4 on 2025-07-31 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_cadeteprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeteprofile',
            name='subscription_info',
            field=models.JSONField(blank=True, help_text='Contiene la información de la suscripción push del navegador del cadete.', null=True, verbose_name='Información de Suscripción WebPush'),
        ),
        migrations.AlterField(
            model_name='clienteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clienteprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productocanje',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta a la imagen estática.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productocanje',
            name='nombre',
            field=models.CharField(help_text='Nombre del producto o descuento a canjear.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productocanje',
            name='puntos_requeridos',
            field=models.PositiveIntegerField(default=0, help_text='Puntos necesarios para canjear.'),
        ),
    ]
