# Generated by Django 5.2.4 on 2025-08-01 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_cadeteprofile_subscription_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cadete_asignado',
            field=models.ForeignKey(blank=True, help_text='El cadete que ha aceptado este pedido.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='pedidos.cadeteprofile'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En Preparación'), ('ASIGNADO', 'Asignado a Cadete'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=20),
        ),
    ]
