# Generated by Django 5.2.4 on 2025-07-03 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_producto_imagen'),
        ('pedidos', '0009_restaurar_admin'),
    ]

    operations = [
    ]
