# Generated by Django 5.2.4 on 2025-08-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_pedido_cadete_asignado_alter_pedido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo_sku', models.CharField(blank=True, default='', max_length=40)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('saldo_inicial_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('ABIERTA', 'ABIERTA'), ('CERRADA', 'CERRADA')], default='ABIERTA', max_length=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('saldo_cierre_efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas_abiertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cajas_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VentaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_comprobante', models.CharField(choices=[('COMANDA', 'Comanda (sin fiscal)'), ('BISTRO', 'Bistró (con factura)')], default='COMANDA', max_length=10)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('QR_MP', 'QR / MercadoPago'), ('TARJETA', 'Tarjeta (déb./créd.)'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=30)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('COMPLETADA', 'COMPLETADA'), ('CANCELADA', 'CANCELADA')], default='COMPLETADA', max_length=12)),
                ('numero_comprobante', models.CharField(blank=True, default='', max_length=60)),
                ('notas', models.TextField(blank=True, default='')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pedidos.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('VENTA', 'VENTA'), ('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO'), ('AJUSTE', 'AJUSTE'), ('RETIRO', 'RETIRO')], max_length=10)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('QR_MP', 'QR / MercadoPago'), ('TARJETA', 'Tarjeta (déb./créd.)'), ('TRANSFERENCIA', 'Transferencia'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion', models.CharField(blank=True, default='', max_length=240)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='pedidos.caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_caja', to='pedidos.ventapos')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VentaPOSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=160)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.productopos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.ventapos')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
