# Generated by Django 5.2.4 on 2025-07-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_merge_0008_producto_imagen_0009_restaurar_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, help_text="Ruta a la imagen estática del producto (ej: 'images/helado_vainilla.png')", max_length=255, null=True),
        ),
    ]
