# Generated by Django 5.2.4 on 2025-08-25 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0012_unique_movimiento_por_venta'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='movimientocaja',
            name='uniq_mov_por_venta_tipo',
        ),
    ]
