# Generated by Django 5.2.4 on 2025-09-02 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_remove_movimientocaja_uniq_mov_por_venta_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventapos',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='caja',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='ventapositem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ventapos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ventapositem',
            name='venta',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='MovimientoCaja',
        ),
        migrations.DeleteModel(
            name='ProductoPOS',
        ),
        migrations.DeleteModel(
            name='VentaPOS',
        ),
        migrations.DeleteModel(
            name='VentaPOSItem',
        ),
    ]
