# Generated by Django 5.2.4 on 2025-09-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_remove_ventapos_caja_remove_movimientocaja_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo calculado del envío (ej: por Google Maps).', max_digits=10),
        ),
    ]
