# Generated by Django 5.2.4 on 2025-09-07 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_pedido_costo_envio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(blank=True, max_length=20, null=True)),
                ('a', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_tipo', models.CharField(choices=[('sistema', 'Sistema'), ('staff', 'Staff'), ('cadete', 'Cadete'), ('cliente', 'Cliente')], default='sistema', max_length=10)),
                ('fuente', models.CharField(blank=True, help_text='Origen del cambio (panel, cadete, webhook_mp, etc.)', max_length=50)),
                ('meta', models.JSONField(blank=True, help_text='Datos auxiliares (ej: payment_id, ip, etc.)', null=True)),
            ],
            options={
                'verbose_name': 'Log de Estado de Pedido',
                'verbose_name_plural': 'Logs de Estado de Pedido',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cadeteprofile',
            options={'verbose_name': 'Perfil de Cadete'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_asignado',
            field=models.DateTimeField(blank=True, help_text='Cuando un cadete acepta el pedido.', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_cancelado',
            field=models.DateTimeField(blank=True, help_text='Cuando el pedido se cancela.', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_en_camino',
            field=models.DateTimeField(blank=True, help_text="Cuando el cadete marca 'en camino'.", null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_en_preparacion',
            field=models.DateTimeField(blank=True, help_text='Cuando la tienda confirma y pasa a preparación.', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, help_text='Cuando el pedido se marca como entregado.', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pago_aprobado',
            field=models.DateTimeField(blank=True, help_text='Momento en que el pago fue aprobado (o creación para efectivo).', null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En Preparación'), ('ASIGNADO', 'Asignado a Cadete'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RECIBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado'], name='pedidos_ped_estado_20cbc4_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['-fecha_pedido'], name='pedidos_ped_fecha_p_0727e9_idx'),
        ),
        migrations.AddField(
            model_name='pedidoestadolog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidoestadolog',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_estado', to='pedidos.pedido'),
        ),
        migrations.AddIndex(
            model_name='pedidoestadolog',
            index=models.Index(fields=['pedido', '-created_at'], name='pedidos_ped_pedido__0d8906_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoestadolog',
            index=models.Index(fields=['a'], name='pedidos_ped_a_61b66e_idx'),
        ),
    ]
