# Generated by Django 5.2.4 on 2025-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_pedidoestadolog_alter_cadeteprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('is_open', models.BooleanField(default=True, help_text='Si está apagado, no se aceptan nuevos pedidos.')),
                ('message', models.CharField(blank=True, help_text='Mensaje opcional para mostrar en la web.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de la tienda',
                'verbose_name_plural': 'Estado de la tienda',
            },
        ),
    ]
