# Generated by Django 5.2.4 on 2025-09-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_storestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value_text', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración global',
                'verbose_name_plural': 'Configuraciones globales',
            },
        ),
    ]
