# Generated by Django 5.2.4 on 2025-09-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_globalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de pago'), ('RECIBIDO', 'Recibido'), ('EN_PREPARACION', 'En Preparación'), ('ASIGNADO', 'Asignado a Cadete'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], db_index=True, default='RECIBIDO', max_length=20),
        ),
    ]
