# Generated by Django 5.2.4 on 2025-09-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='orden_todos',
            field=models.PositiveIntegerField(db_index=True, default=1000, help_text="Posición en la vista 'Todos'. Menor sale antes."),
        ),
    ]
