# Generated by Django 5.2.4 on 2025-09-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0020_producto_orden_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='nota',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
